name: GitHub Action
run-name: Test action
on: [push]
permissions: write-all

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: getPr
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Call OpenAI API
        id: gpt
        run: |
          url="https://patch-diff.githubusercontent.com/raw/natdeanlewissoftwire/submit-social-housing-lettings-and-sales-data/pull/${{ steps.findPr.outputs.pr }}.diff"
          text=$(curl -s $url)
          response=$(curl https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPEN_AI_API_KEY }}" \
            -d '{
            "model": "text-davinci-003",
            "prompt": "Here is a pull request diff in Ruby:\n \"\"\"\ndiff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml\nnew file mode 100644\nindex 000000000..7bc71f2cc\n--- /dev/null\n+++ b/.github/workflows/github-actions-demo.yml\n@@ -0,0 +1,37 @@\n+name: GitHub Action\n+run-name: Test action\n+on: [push]\n+permissions: write-all\n+\n+jobs:\n+  test-action:\n+    runs-on: ubuntu-latest\n+\n+    steps:\n+      - name: Checkout code\n+        uses: actions/checkout@v2\n+      - name: Call OpenAI API\n+        id: gpt\n+        run: |\n+          response=$(curl https://api.openai.com/v1/completions \\\n+            -H \"Content-Type: application/json\" \\\n+            -H \"Authorization: Bearer ${{ secrets.OPEN_AI_API_KEY }}\" \\\n+            -d '{\n+            \"model\": \"text-davinci-003\",\n+            \"prompt\": \"Here is a pull request diff in Ruby:\\nCODE\\nGive me a sentence summarising what this diff does, and then write a few (no more than 5) bullet points explaining what this diff does in more detail. These bullet points should cover any major changes. Then find any possible bugs and suggest any improvements to the code if there are any obvious errors (otherwise write \\\"None\\\").\\n\\nUse the following template for your output:\\n\\nSummary: <summary sentence goes here>\\n\\nIn more detail: <bullet points go here>\\n\\nPossible bugs/suggested improvements: <possible bugs and suggested improvements go here>\\n\\n\",\n+            \"temperature\": 0,\n+            \"max_tokens\": 376,\n+            \"top_p\": 1,\n+            \"frequency_penalty\": 0,\n+            \"presence_penalty\": 0,\n+            \"stop\": [\"\\\"\\\"\\\"\"]\n+          }')\n+          echo $response | jq\n+          test=\"test\"\n+      - uses: jwalton/gh-find-current-pr@v1\n+        id: findPr\n+      - uses: peter-evans/create-or-update-comment@v2.1.1\n+        with:\n+          issue-number: 5\n+          body: ${{ steps.gpt.outputs.response.choices.text }}\n+          reactions: 'rocket'\n\"\"\"\nGive me a sentence summarising what this diff does, and then write a few (no more than 5) bullet points explaining what this diff does in more detail. These bullet points should cover any major changes. Then find any possible bugs and suggest any improvements to the code if there are any obvious errors (otherwise write \"None\").\n\nUse the following template for your output:\n\nSummary: <summary sentence goes here>\n\nIn more detail: <bullet points go here>\n\nPossible bugs/suggested improvements: <possible bugs and suggested improvements go here>",
            "temperature": 0,
            "max_tokens": 376,
            "top_p": 1,
            "frequency_penalty": 0,
            "presence_penalty": 0,
            "stop": ["\"\"\""]
          }')
          echo $response | jq
          response_text=$(cat response | jq '.choices | .[0] | .text')
          echo "response=$response" >> $GITHUB_OUTPUT
          echo "response_text=$response_text" >> $GITHUB_OUTPUT

      - uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: |
            ${{ steps.gpt.outputs.response_text }}
            ${{ fromJson(steps.gpt.outputs.response).choices[0].text }}

          reactions: 'rocket'
