name: GitHub Action
run-name: Test action
on: [push]
permissions: write-all

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: 5
          body: |
            https://patch-diff.githubusercontent.com/raw/${{ github.repository }}/pull/${{ steps.findPr.outputs.pr }}.diff
          reactions: 'rocket'
  openai_chatgpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Call OpenAI API
        run: |
          curl https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
            "model": "text-davinci-003",
            "prompt": "Here is a pull request diff in Ruby:\n\n\"\"\"\ndiff --git a/app/models/form/lettings/questions/rsnvac.rb b/app/models/form/lettings/questions/rsnvac.rb\nindex 4968ebb2db..2899a94633 100644\n--- a/app/models/form/lettings/questions/rsnvac.rb\n+++ b/app/models/form/lettings/questions/rsnvac.rb\n@@ -36,6 +36,9 @@ def initialize(id, hsh, page)\n     \"18\" => {\n       \"value\" => \"Tenant moved to care home\",\n     },\n+    \"20\" => {\n+      \"value\" => \"Tenant moved to long-stay hospital or similar institution\",\n+    },\n     \"6\" => {\n       \"value\" => \"Tenant abandoned property\",\n     },\ndiff --git a/spec/models/form/lettings/questions/rsnvac_spec.rb b/spec/models/form/lettings/questions/rsnvac_spec.rb\nnew file mode 100644\nindex 0000000000..302f566fe9\n--- /dev/null\n+++ b/spec/models/form/lettings/questions/rsnvac_spec.rb\n@@ -0,0 +1,79 @@\n+require \"rails_helper\"\n+\n+RSpec.describe Form::Lettings::Questions::Rsnvac, type: :model do\n+  subject(:question) { described_class.new(question_id, question_definition, page) }\n+\n+  let(:question_id) { nil }\n+  let(:question_definition) { nil }\n+  let(:page) { instance_double(Form::Page) }\n+\n+  it \"has correct page\" do\n+    expect(question.page).to eq(page)\n+  end\n+\n+  it \"has the correct id\" do\n+    expect(question.id).to eq(\"rsnvac\")\n+  end\n+\n+  it \"has the correct header\" do\n+    expect(question.header).to eq(\"What is the reason for the property being vacant?\")\n+  end\n+\n+  it \"has the correct check_answer_label\" do\n+    expect(question.check_answer_label).to eq(\"Vacancy reason\")\n+  end\n+\n+  it \"has the correct type\" do\n+    expect(question.type).to eq(\"radio\")\n+  end\n+\n+  it \"is not marked as derived\" do\n+    expect(question.derived?).to be false\n+  end\n+\n+  it \"has the correct answer_options\" do\n+    expect(question.answer_options).to eq({\n+      \"13\" => {\n+        \"value\" => \"Internal transfer\",\n+        \"hint\" => \"Excluding renewals of a fixed-term tenancy\",\n+      },\n+      \"5\" => {\n+        \"value\" => \"Previous tenant died with no succession\",\n+      },\n+      \"9\" => {\n+        \"value\" => \"Re-let to tenant who occupied same property as temporary accommodation\",\n+      },\n+      \"14\" => {\n+        \"value\" => \"Renewal of fixed-term tenancy\",\n+      },\n+      \"19\" => {\n+        \"value\" => \"Tenant involved in a succession downsize\",\n+      },\n+      \"8\" => {\n+        \"value\" => \"Tenant moved to private sector or other accommodation\",\n+      },\n+      \"12\" => {\n+        \"value\" => \"Tenant moved to other social housing provider\",\n+      },\n+      \"18\" => {\n+        \"value\" => \"Tenant moved to care home\",\n+      },\n+      \"20\" => {\n+        \"value\" => \"Tenant moved to long-stay hospital or similar institution\",\n+      },\n+      \"6\" => {\n+        \"value\" => \"Tenant abandoned property\",\n+      },\n+      \"10\" => {\n+        \"value\" => \"Tenant was evicted due to rent arrears\",\n+      },\n+      \"11\" => {\n+        \"value\" => \"Tenant was evicted due to anti-social behaviour\",\n+      },\n+    })\n+  end\n+\n+  it \"has the correct check_answers_card_number\" do\n+    expect(question.check_answers_card_number).to eq(0)\n+  end\n+end\n\n\"\"\"\n\nGive me a sentence summarising what this diff does, and then write a few (no more than 5) bullet points explaining what this diff does in more detail. These bullet points should cover any major changes. Then find any possible bugs and suggest any improvements to the code if there are any obvious errors (otherwise write \"None\").\n\nUse the following template for your output:\n\nSummary: <summary sentence goes here>\n\nIn more detail: <bullet points go here>\n\nPossible bugs/suggested improvements: <possible bugs and suggested improvements go here>\n\n",
            "temperature": 0,
            "max_tokens": 376,
            "top_p": 1,
            "frequency_penalty": 0,
            "presence_penalty": 0,
            "stop": ["\"\"\""]
          }'
