name: GitHub Action
run-name: Test action
on: [push]
permissions: write-all

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:

      - name: Create or Update Comment
      - uses: actions/checkout@v1
# Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number

        uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: 5
          body: |
            https://patch-diff.githubusercontent.com/raw/${{ github.repository }}/pull/${{ steps.findPr.outputs.pr }}.diff
          reactions: 'rocket'
